CREATE DATABASE CLASE_7; --ARMAMOS BASE Y TABLA

CREATE TABLE  Clientes(N_Cliente  int NOT NULL PRIMARY KEY, Nombre varchar(20) NOT NULL, Sexo varchar(1) NOT NULL,Telefono varchar(10) NOT NULL,ID_Edad int NOT NULL);

INSERT INTO Clientes VALUES (345,'Juan', 'M','34484056',8), (390,'Mariela', 'F','45835000',9), (398,'Cristian', 'M','45786349',1), (562,'Fernando', 'M','42568360',3),(610,'Fernando', 'M','42568360',3),(817,'Silvana', 'F','32583159',5);

SELECT * FROM Clientes;

-- USAMOS DISTINCT PARA TRAER DISTINTOS

SELECT DISTINCT Nombre, Sexo FROM Clientes;

--USAMOS AS PARA NOMBRAR ALGO, NO CAMBIA LA ESTRUCTURA, SOLO VISUALIZACION

SELECT N_Cliente AS Usuario, Nombre AS Cliente, Sexo AS GeneroFROM Clientes;

--USOS DEL WHERESELECT N_Cliente AS ID, Nombre FROM ClientesWHERE N_Cliente > 400;

SELECT * FROM ClientesWHERE Nombre LIKE '%a'; --NOMBRE TERMINA CON A 

SELECT * FROM ClientesWHERE Nombre LIKE 'f%' OR N_Cliente = 562; --USAMOS OR, ANDSELECT * FROM ClientesWHERE Nombre LIKE 'f%' AND N_Cliente = 562; --NOMBRE EMPIEZA CON A 

SELECT N_Cliente, ID_Edad, N_Cliente + ID_Edad AS Nuevo_ID --SUMA COLUMNASFROM Clientes;

--ORDER BY Y TOP

SELECT TOP(2) * --TOP ES CANTIDAD DE REGISTROS MAXIMO QUE ME DEVUELVAFROM ClientesORDER BY ID_Edad DESC; --ASC AUTOMATICO

SELECT TOP(2) *FROM ClientesORDER BY N_Cliente DESC;

SELECT N_Cliente AS ID, Nombre, Sexo, Telefono --USA EL ASFROM ClientesORDER BY ID DESC;

--UTILIZO FUNCIONES Y GROUP BY 

SELECT Sexo, --AGRUPO POR LO QUE SELECCIONO AL PRINCIPIOCOUNT(N_Cliente) AS Cant_Clientes --SIEMPRE USAR ASFROM CLIENTES --COUNT CUENTA CANTIDAD QUE CUMPLEGROUP BY Sexo;

--UTILIZO HAVING COMO EL WHERE PARA FUNCIONES Y GROUP BY
--AVG, SUM, COUNT, MAX, MIN

SELECT Sexo, COUNT(N_Cliente) AS Cant_Clientes FROM CLIENTES GROUP BY Sexo
HAVING COUNT(N_Cliente) > 3; --NO SE PUEDE APLICAR SOBRE EL AS, SIEMPRE EL NOMBRE DE LA FUNCION 

--PUEDO UTILIZAR AND Y OR PARA HAVING (MAS CONDICIONES)

SELECT COUNT(N_cliente) AS Cantidad,Nombre FROM ClientesGROUP BY NombreHAVING Nombre LIKE '%a';
