--CREAR BASE DE DATOS, ESCRIBIR EN MASTER LA BASE

CREATE DATABASE CLASE_4;

--ESCRIBIR EN CLASE 4 
--NOT NULL PARA QUE NO ESTE VACIO, IDENTITY AUTOINCREMENTAL (OBLIGATORIO EN LA PK)
--DEFINIR QUE TIPO DE DATO PUEDO PONER EN LAS COLUMNAS Y LA CANTIDAD (NOT NULL NO OBLIGATORIO)

CREATE TABLE CLIENTES (IDCliente int NOT NULL IDENTITY PRIMARY KEY, NombreCliente varchar(50) NOT NULL, Direccion varchar(50) NOT NULL,Ciudad varchar(50) NOT NULL, CP varchar(50) NOT NULL, Pais text NOT NULL);

-- CREAR TABLA EMPLEADOS --CREATE TABLE Empleados (IDEmpleado int NOT NULL IDENTITY PRIMARY KEY, Apellido varchar(50) NOT NULL, Nombre varchar(50) NOT NULL,Nacimiento datetime NOT NULL, Notas varchar(50)NOT NULL);

--CREAR TABLA ORDENES QUE DEPENDE DE LAS OTRAS DOS, LOS ELEMENTOS DE LAS TABLAS ORIGINALES TIENE QUE ESTAR EXACTAMENTE IGUAL DEFINIDOS

CREATE TABLE Ordenes (IDOrden int NOT NULL IDENTITY PRIMARY KEY, FechaOrden datetime NOT NULL, IDCliente int NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),IDEmpleado int NOT NULL FOREIGN KEY REFERENCES Empleados(IDEmpleado));

--AGREGAR COLUMNA CANTIDAD CON ALTER, SI NO PONGO NOT NULL PERMITE NULL --ALTER TABLE OrdenesADD Cantidad int;

--MODIFICAR TIPO DE DATOS DE COLUMNA--ALTER TABLE OrdenesALTER COLUMN Cantidad varchar(50);

--ELIMINAR COLUMNA, ALTER Y DROP, NO SE PUEDE VOLVER A RECUPERAR, PUEDO USAR DROP TABLE ALTER TABLE OrdenesDROP COLUMN Cantidad;

--CAMBIAR NOMBRE DE TABLA

ALTER TABLE NombreActual RENAME TO NuevoNombre;



